FROM sgtwilko/rpi-raspbian-opencv:latest
#FROM mohaseeb/raspberrypi3-python-opencv:latest

WORKDIR /src

COPY requirements.txt /src/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY src/ /src

CMD ["/bin/bash"]
